### ISSUE TITLE
First Steps

### ISSUE THREAD

**Issue by Gab0** [haamis/neuro_classifier#1]
Hey, could you give some hints on how to use it?
Like how the articles should be stored, how to proceed on the training if needed...
Seems a cool project!
Thanks.

**Comment by haamis** [comment]
Hi,
The code in [pubmed_processing](https://github.com/haamis/pubmed_processing) deals with preprocessing the [data downloaded from pubmed](ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline). The relevant information is written to JSON files, one .json file per xml file, and then combined to one big .json file by a bash script for easier human readability. This data is then read by the `preprocess_[binary,multilabel].py` script that dumps the abstracts and labels into separate files using pickle. The `preprocess_binary.py` script also reads in a JSON file containing the MeSH terms to be considered as positive labels for the binary classification (in my case, a list of MeSH terms related to neuroscience).
So, the code in this repository loads in the pickled list of abstracts as one command line argument and the pickled list of labels corresponding to each abstract as the second argument. It then does some more processing on the data (tokenizing and vectorizing the abstracts, binarizing the labels) and proceeds to train a model on that data. For example: `python3 binary/bert_keras_binary.py <abstracts_file> <binary_labels_file>`.

Hope this helps. The code and the workflow are kinda messy as it is a project I've been coding alone and learning/experimenting as I go.
